package cleanfill.utilities;

public interface ExcelColumns {

    // Credentials
    int SOURCE_SITE_USERNAME = 0;
    int SOURCE_SITE_PASSWORD = 1;
    int RECEIVING_SITE_USERNAME = 3;
    int RECEIVING_TYPE_PASSWORD = 4;

    // Create Batch
    int EST_START_DATE = 1;
    int BATCH_NAME = 2;
    int TRACK_BY = 3;
    int EST_LOADS = 4;
    int EST_WEIGHT = 5;
    int EST_VOLUME = 6;
    int OTHER_SOURCE_TYPE = 7;
    int SOURCE_TYPE_OTHERS = 8;
    int SOURCE_SITE_HISTORY = 9;
    int SOURCE_SITE_HISTORY_OTHER = 10;
    int PRESENT_USE = 11;
    int SOIL_DESCRIPTION = 12;
    int SOIL_PARAMETERS = 13;
    int SOIL_PARAMETERS_OTHER = 14;
    int FILE_UPLOAD = 15;
    int FILE_LINK = 16;
    int COMMENT = 17;

    // Signup
    int SIGNUP_EMAIL = 1;
    int SIGNUP_PASSWORD = 2;
    int SIGNUP_GIVENNAME = 3;
    int SIGNUP_SURNAME = 4;

    // Source Site Signup
    int SOURCE_COMPANY_NAME = 5;
    int SOURCE_COMPANY_ADDRESS = 6;
    int SOURCE_COMPANY_MUNICIPALITY = 7;
    int SOURCE_PHONE_NUMBER = 8;
    int SOURCE_EXTENSION = 9;
    int SOURCE_SITE_NAME = 10;
    int SOURCE_SITE_ADDRESS = 11;
    int SOURCE_SITE_MUNICIPALITY = 12;
    int SOURCE_SITE_FULL_NAME = 13;
    int SOURCE_SITE_EMAIL_ID = 14;
    int SOURCE_SITE_PHONE_NUMBER = 15;
    int SOURCE_SITE_EXTENSION = 16;
    int SOURCE_SITE_FILE_UPLOAD = 17;
    int SOURCE_PERSONAL_FULL_NAME = 18;
    int SOURCE_PERSONAL_EMAIL_ID = 19;
    int SOURCE_PERSONAL_PHONE_NUMBER = 20;
    int SOURCE_PERSONAL_EXTENSION = 21;
    int SOURCE_BILLING_SAME_AS_PERSONAL = 22;
    int SOURCE_BILLING_FULL_NAME = 23;
    int SOURCE_BILLING_EMAIL_ID = 24;
    int SOURCE_BILLING_PHONE_NUMBER = 25;
    int SOURCE_BILLING_EXTENSION = 26;

    // Receiving Site Signup
    int RECEIVING_COMPANY_NAME = 5;
    int RECEIVING_COMPANY_ADDRESS = 6;
    int RECEIVING_COMPANY_MUNICIPALITY = 7;
    int RECEIVING_PHONE_NUMBER = 8;
    int RECEIVING_EXTENSION = 9;
    int RECEIVING_SITE_NAME = 10;
    int RECEIVING_SITE_NUMBER = 11;
    int RECEIVING_SITE_ADDRESS = 12;
    int RECEIVING_SITE_MUNICIPALITY = 13;
    int RECEIVING_SITE_FULL_NAME = 14;
    int RECEIVING_SITE_EMAIL_ID = 15;
    int RECEIVING_SITE_PHONE_NUMBER = 16;
    int RECEIVING_SITE_EXTENSION = 17;
    int RECEIVING_SITE_VISIBILITY = 18;
    int RECEIVING_SITE_THIRD_PARTY_REPORTING = 19;
    int RECEIVING_SITE_SOIL_CLASSIFICATION = 20;
    int RECEIVING_SITE_FILE_UPLOAD = 21;
    int RECEIVING_PERSONAL_FULL_NAME = 22;
    int RECEIVING_PERSONAL_EMAIL_ID = 23;
    int RECEIVING_PERSONAL_PHONE_NUMBER = 24;
    int RECEIVING_PERSONAL_EXTENSION = 25;
    int RECEIVING_BILLING_SAME_AS_PERSONAL = 26;
    int RECEIVING_BILLING_FULL_NAME = 27;
    int RECEIVING_BILLING_EMAIL_ID = 28;
    int RECEIVING_BILLING_PHONE_NUMBER = 29;
    int RECEIVING_BILLING_EXTENSION = 30;

    // QP Signup
    int QP_COMPANY_NAME = 5;
    int QP_PGO = 6;
    int QP_COMPANY_ADDRESS = 7;
    int QP_COMPANY_MUNICIPALITY = 8;
    int QP_PHONE_NUMBER = 9;
    int QP_EXTENSION = 10;
    int QP_PERSONAL_FULL_NAME = 11;
    int QP_PERSONAL_EMAIL_ID = 12;
    int QP_PERSONAL_PHONE_NUMBER = 13;
    int QP_PERSONAL_EXTENSION = 14;

}